# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "GreetingLib",
    srcs = glob(["**/*.c*"]),
    hdrs = glob(["**/*.h*"]),
    visibility = ["//visibility:public"],
)
